project:
  type: website
  output-dir: docs

website:
  title: "Venezuela Libre Data"
  page-footer:
    background: '#2596be'
    left: "VLD, 2024"
    right:
      - icon: envelope
        text: "contacto {{< fa envelope >}} : venezuelalibredata@protonmail.com"
        href: "mailto:venezuelalibredata@protonmail.com"
  navbar:
    logo: img/ven.png
    style: "docked"
    fontsize: 30px
    left:
      - href: index.qmd
        text: VLD
      - href: resulestado.qmd
        text: Resultados por Estado
      - href: resulmunicipio.qmd
        text: Resultados por Municipio
      - href: downloads.qmd
        text: Zona Descarga
      - href: schema.qmd
        text: Esquema de Datos
      - href: about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    # toc: true
    dark: darkly
    page-layout: full
    include-in-header: gtm_code_head.html
    include-before-body: gtm_code_body.html

editor: visual

